name: Ejecutar comandos personalizados

on:
  workflow_dispatch:
    inputs:
      comando:
        description: 'El comando que deseas ejecutar'
        required: true
        default: 'echo "Comando por defecto"'

jobs:
  ejecutar_comando:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar el comando personalizado
        run: ${{ github.event.inputs.comando }}
