name: Build .NET Solution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Puedes cambiar esto por 'windows-latest' o 'macos-latest' según sea necesario.

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # Cambia esta versión si usas una diferente.

      # Paso 3: Restaurar dependencias
      - name: Restore dependencies
        run: dotnet restore Syndical.sln

      # Paso 4: Compilar la solución
      - name: Build the solution
        run: dotnet build Syndical.sln --configuration Release

      # Paso 5: Ejecutar pruebas (opcional)
      - name: Run tests
        run: dotnet test Syndical.sln --configuration Release

      # Paso 6: Subir el artefacto de la compilación
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: syndical-build # Nombre del artefacto que aparecerá en GitHub
          path: |
            TheAirBlow.Syndical.Application/bin/Release/net6.0/*  # Cambia el camino dependiendo de tu estructura de salida
            TheAirBlow.Syndical.Library/bin/Release/net6.0/*      # Aquí deberías incluir las salidas de todos los proyectos de la solución
